/*
 * Copyright (C) 2014 Yoan Pratama Putra
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package fridge;

/**
 *
 * @author Yoan Pratama Putra
 */
public class Main extends javax.swing.JFrame{

    /**
     * Creates new form Main
     */
    private Fridge server;
    public static int temperature;
    public static Thread tempThread;
    
    // ubah suhu
    public static void changeTemperature() {
        txtTemperature.setText(Integer.toString(temperature));
    }
    
    // ambil suhu untuk client
    public static int getTemperature() {
        return Integer.parseInt(txtTemperature.getText());
    }
    
    public Main() {
        initComponents();
        temperature = 4;
        this.setTitle("Fridge");
        try {
            server = new Fridge();
        } catch(Exception ex) {
            System.out.println("Server: " + ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCelcius = new javax.swing.JLabel();
        btnSwitch = new javax.swing.JToggleButton();
        btnTempMin = new javax.swing.JButton();
        txtTemperature = new javax.swing.JLabel();
        btnTempMax = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCelcius.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblCelcius.setText("°C");

        btnSwitch.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnSwitch.setText("Turn on");
        btnSwitch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSwitchActionPerformed(evt);
            }
        });

        btnTempMin.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnTempMin.setText("-");
        btnTempMin.setEnabled(false);
        btnTempMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTempMinActionPerformed(evt);
            }
        });

        txtTemperature.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtTemperature.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtTemperature.setText("4");

        btnTempMax.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnTempMax.setText("+");
        btnTempMax.setEnabled(false);
        btnTempMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTempMaxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSwitch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
                .addComponent(txtTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCelcius)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTempMin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTempMax)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCelcius)
                    .addComponent(btnTempMin)
                    .addComponent(txtTemperature)
                    .addComponent(btnTempMax)
                    .addComponent(btnSwitch))
                .addContainerGap(306, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void btnSwitchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSwitchActionPerformed
        try {
            if(this.btnSwitch.getText().equals("Turn on")) {
                // menghidupkan kulkas dan menjalankan RMI
                server.start();
                this.setTitle("Fridge [" + server.getStatus() + "]");
                this.btnSwitch.setText("Turn off");
                this.btnTempMin.setEnabled(true);
                this.btnTempMax.setEnabled(true);
            } else {
                // mematikan kulkas dan menghentikan RMI
                server.stop();
                this.setTitle("Fridge");
                this.btnSwitch.setText("Turn on");
                this.btnTempMin.setEnabled(false);
                this.btnTempMax.setEnabled(false);
            }
        } catch(Exception ex) {
            System.out.println("Failed: " + ex);
            this.btnSwitch.setSelected(false);
        }
    }//GEN-LAST:event_btnSwitchActionPerformed

    private void btnTempMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTempMinActionPerformed
        // cek apakah suhu > -20
        if(temperature > -20) {
            // kurangi suhu
            temperature--;
            txtTemperature.setText(Integer.toString(temperature));
        }
    }//GEN-LAST:event_btnTempMinActionPerformed

    private void btnTempMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTempMaxActionPerformed
        // cek apakah suhu < 4
        if(temperature < 4) {
            // tambah suhu
            temperature++;
            txtTemperature.setText(Integer.toString(temperature));
        }
    }//GEN-LAST:event_btnTempMaxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
                
                // buat dan jalankan thread suhu
                temperatureThread tempThread = new temperatureThread();
                tempThread.start();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnSwitch;
    private javax.swing.JButton btnTempMax;
    private javax.swing.JButton btnTempMin;
    private javax.swing.JLabel lblCelcius;
    private static javax.swing.JLabel txtTemperature;
    // End of variables declaration//GEN-END:variables

}
